services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    environment:
      BUNDLE_PATH: /usr/local/bundle

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
  bundle_data:
